#!/usr/bin/env zsh

# Purge history

# usage:
#
# $ clearhis
function clearhis {
    srm $HISTFILE
    srm $ZDOTDIR/cache/zdirdump
    clear
    if test -n ${TMUX}; then
      tmux clear-history
    fi
}
